#!/usr/bin/env python3
"""Render the AtlasGB pages from `data/atlas.tsv`.

Every table, index, count and coverage figure in `docs/` and in the repository
README is written by this script from the one data file, so a number in the
prose cannot drift away from the map it describes.  Prose is *not* generated:
each page keeps everything outside its `<!-- atlas:… -->` markers, so the
writing and the tables live in the same file and only one of them is
machine-owned.

    tools/render.py            # rewrite the generated blocks
    tools/render.py --check    # fail if any block is stale

`--check` runs in CI from `make check`.

Anchors: every entry gets `<a id="s-SYMBOL">` on its chapter page and
`<a id="a-XXXX">` on the address index, so any address in the game can be linked
to directly — `docs/party.md#s-wPartyCount`.  Those anchors are the repository's
public URL surface: they are derived from the symbol name and the address, so
they survive regeneration and may be linked to from outside.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chapters as chapters_mod  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR = os.path.join(REPO, "docs")
ATLAS = os.path.join(REPO, "data", "atlas.tsv")

BEGIN = "<!-- atlas:begin ({}) — generated by tools/render.py from data/atlas.tsv; edit the data, not the table -->"
END = "<!-- atlas:end ({}) -->"

REGION_ORDER = ["VRAM", "SRAM", "WRAM0", "HRAM", "ROM0", "ROMX"]
REGION_TITLE = {
    "VRAM": ("Video RAM", "$8000-$9FFF", "The tiles and tilemaps the picture is made of."),
    "SRAM": ("Cartridge RAM", "$A000-$BFFF", "Battery-backed, banked: this is what a `.sav` is."),
    "WRAM0": ("Work RAM", "$C000-$DFFF", "Everything the game is currently thinking."),
    "HRAM": ("High RAM", "$FF80-$FFFE", "127 bytes reachable one byte faster than anything else."),
    "ROM0": ("ROM bank 0", "$0000-$3FFF", "Always mapped: the home bank."),
    "ROMX": ("Switched ROM", "$4000-$7FFF", "One of 63 banks at a time; where the game's data lives."),
}
REGION_SPAN = {
    "VRAM": (0x8000, 0x9FFF),
    "SRAM": (0xA000, 0xBFFF),
    "WRAM0": (0xC000, 0xDFFF),
    "HRAM": (0xFF80, 0xFFFE),
}


# ---------------------------------------------------------------------------
# reading
# ---------------------------------------------------------------------------


def read_atlas():
    rows = []
    header = None
    with open(ATLAS, encoding="utf-8") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if line.startswith("#") or not line.strip():
                continue
            fields = line.split("\t")
            if header is None:
                header = fields
                continue
            row = dict(zip(header, fields))
            row["addr_i"] = int(row["addr"][1:], 16)
            row["len_i"] = int(row["len"] or 0)
            rows.append(row)
    return rows


def addr_of(rows, symbol):
    for r in rows:
        if r["symbol"] == symbol:
            return r["addr_i"]
    return None


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------


def size(n: int) -> str:
    if n == 0:
        return "—"
    if n == 1:
        return "1"
    return str(n)


def evidence(v: str) -> str:
    """Render the verify column as the short badges the pages explain once."""
    if not v:
        return "·"
    toks = [t for t in v.split(",") if t]
    marks = {"rom": "R", "live": "L", "inv": "I"}
    return "".join(marks.get(t, "?") for t in toks)


def is_synthetic(row) -> bool:
    return row["role"] in ("gap", "free")


def display_symbol(row) -> str:
    if row["role"] == "gap":
        return "*(no label reaches here)*"
    if row["role"] == "free":
        return "*(unallocated)*"
    return f"`{row['symbol']}`"


def slot_name(symbol: str, k: int):
    """The name slot `k` of `symbol`'s family would have, or None.

    pokered numbers repeated structures both ways — `wPartyMon1`..`wPartyMon6`
    and the zero-padded `wSprite01`..`wSprite15` — so the width of the digit run
    has to be carried across, or every sprite slot is treated as its own entry
    and the page lists 49 of them in full.
    """
    i = 0
    while i < len(symbol):
        if symbol[i].isdigit():
            j = i
            while j < len(symbol) and symbol[j].isdigit():
                j += 1
            if int(symbol[i:j]) == 1:
                width = j - i
                yield symbol[:i] + str(k).zfill(width) + symbol[j:]
            i = j
        else:
            i += 1


def family(rows_by_symbol, row):
    """(slot count, stride) for a repeated structure whose slot 1 this row is."""
    sym = row["symbol"]
    stride = None
    n = 1
    for k in range(2, 41):
        hit = next((c for c in slot_name(sym, k) if c in rows_by_symbol), None)
        if hit is None:
            break
        if k == 2:
            stride = rows_by_symbol[hit]["addr_i"] - row["addr_i"]
        n = k
    return n, stride


def block(name: str, lines: list[str]) -> str:
    return "\n".join([BEGIN.format(name), "", *lines, "", END.format(name)])


def coverage_block(rows) -> str:
    out = [
        "| region | span | bytes | named by a symbol | reached by no label | unallocated |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for region in ("VRAM", "SRAM", "WRAM0", "HRAM"):
        lo, hi = REGION_SPAN[region]
        span = hi - lo + 1
        banks = sorted({r["bank"] for r in rows if r["region"] == region})
        for bank in banks:
            named = bytearray(span)
            gap = bytearray(span)
            free = bytearray(span)
            for r in rows:
                if r["region"] != region or r["bank"] != bank:
                    continue
                target = {"gap": gap, "free": free}.get(r["role"], named)
                for a in range(r["addr_i"], r["addr_i"] + max(r["len_i"], 1)):
                    if lo <= a <= hi:
                        target[a - lo] = 1
            n_named = sum(named)
            n_gap = sum(1 for i in range(span) if gap[i] and not named[i])
            n_free = sum(1 for i in range(span) if free[i] and not named[i] and not gap[i])
            label = REGION_TITLE[region][0]
            if len(banks) > 1:
                label += f" bank {bank}"
            out.append(
                f"| {label} | `{REGION_TITLE[region][1]}` | {span:,} | "
                f"{n_named:,} | {n_gap:,} | {n_free:,} |"
            )
    return block("coverage", out)


def evidence_block(rows) -> str:
    storage = [r for r in rows if r["region"] not in ("ROM0", "ROMX")]
    def n(tok):
        return sum(1 for r in storage if tok in r["verify"].split(","))
    none = sum(1 for r in storage if not r["verify"])
    entries_only = [r for r in rows if r["role"] == "entry"]
    distinct = len(entries_only)
    described = sum(1 for r in entries_only if r["desc"])
    out = [
        "| evidence | entries | what it means |",
        "|---|---:|---|",
        f"| **R** — the cartridge names it | {n('rom'):,} | the address appears as the operand of an "
        "instruction in the ROM image |",
        f"| **L** — observed live | {n('live'):,} | the byte changed while the cartridge ran a fixed "
        "script on this emulator |",
        f"| **I** — an invariant covers it | {n('inv'):,} | a named check proved it means what the "
        "atlas says it means |",
        f"| *(none)* | {none:,} | no evidence yet — stated, not hidden |",
        "",
        f"Storage entries in total: **{len(storage):,}**.",
        "",
        f"Written descriptions cover **{described:,} of the {distinct:,} distinct addresses** "
        f"({100 * described // max(distinct, 1)}%). The rest carry their symbol name and their "
        "evidence and nothing more, which is the honest state of them — every chapter page "
        "reports its own figure at the top of its table.",
    ]
    return block("evidence", out)


def chapter_index_block(rows, prefix: str = "") -> str:
    """The chapter index.

    `prefix` is where the chapter pages sit relative to the page being written:
    empty from inside `docs/`, `docs/` from the repository README.
    """
    counts = {}
    for r in rows:
        counts[r["group"]] = counts.get(r["group"], 0) + 1
    out = ["| chapter | entries | what is in it |", "|---|---:|---|"]
    for name, blurb in chapters_mod.CHAPTERS.items():
        if name not in counts:
            continue
        out.append(f"| [{name}]({prefix}{name}.md) | {counts[name]:,} | {blurb} |")
    return block("chapters", out)


def chapter_table(rows, chapter: str) -> str:
    by_symbol = {r["symbol"]: r for r in rows}
    mine = [r for r in rows if r["group"] == chapter]
    mine.sort(key=lambda r: (REGION_ORDER.index(r["region"]), r["bank"], r["addr_i"]))
    # Say how much of this chapter carries a written description. A page that
    # is 7 of 177 described should say so on its own face rather than let a
    # reader infer completeness from a full-looking table.
    entries_here = [r for r in mine if r["role"] == "entry"]
    described = sum(1 for r in entries_here if r["desc"])
    total_rows = len(mine)
    folded = sum(1 for r in mine if r["role"] == "instance")
    bits = [
        f"**{total_rows:,} entries**",
        f"{len(entries_here):,} distinct addresses",
        f"**{described:,} with a written description**",
    ]
    if folded:
        bits.append(f"{folded:,} repeated slots folded onto slot 1")
    out = [
        " · ".join(bits) + ".",
        "",
        "| address | bytes | symbol | ev | what it is |",
        "|---|---:|---|:--:|---|",
    ]
    # Aliases are folded onto the row of the entry they alias; instances are
    # folded onto slot 1 with a count, because a table with wBoxMon2Species
    # through wBoxMon20Special in it is a table nobody reads.
    aliases: dict[tuple, list[dict]] = {}
    for r in mine:
        if r["role"] == "alias":
            aliases.setdefault((r["region"], r["bank"], r["addr_i"]), []).append(r)
    for r in mine:
        if r["role"] in ("alias", "instance"):
            continue
        key = (r["region"], r["bank"], r["addr_i"])
        also = aliases.get(key, [])
        sym = display_symbol(r)
        if r["role"] == "entry":
            sym = f'<a id="s-{r["symbol"]}"></a>`{r["symbol"]}`'
        if also:
            # Aliases get their own anchor too: the indexes link every name to
            # `#s-NAME`, so a name without one is a dead link, and `wPartyMons`
            # is exactly the kind of alias a reader arrives by.
            sym += "<br>" + " ".join(
                f'<a id="s-{a["symbol"]}"></a>`{a["symbol"]}`' for a in also
            )
        # An alias may be the name that carries the explanation — `wPartyMons`
        # is an alias of `wPartyMon1Species` — so the cell gathers every
        # description at this address rather than only the entry's.
        notes = [(r["symbol"], r["desc"])] + [(a["symbol"], a["desc"]) for a in also]
        notes = [(n, d) for n, d in notes if d]
        if len(notes) == 1:
            note = notes[0][1]
        elif notes:
            note = " ".join(f"**`{n}`** — {d}" for n, d in notes)
        else:
            note = ""
        slots, stride = family(by_symbol, r) if r["role"] == "entry" else (1, None)
        if slots > 1:
            tail = f"\u00d7{slots}" + (f", stride {stride}" if stride else "")
            note = (note + " " if note else "") + f"*({tail})*"
        bank = "" if r["bank"] == "-" else f" b{r['bank']}"
        out.append(
            f"| `{r['addr']}`{bank} | {size(r['len_i'])} | {sym} | "
            f"{evidence(r['verify'])} | {note} |"
        )
    return block("table", out)


def address_index_block(rows) -> str:
    listed = [r for r in rows if r["role"] != "instance"]
    listed.sort(key=lambda r: (REGION_ORDER.index(r["region"]), r["bank"], r["addr_i"], r["symbol"]))
    out = ["| address | symbol | chapter | ev |", "|---|---|---|:--:|"]
    for r in listed:
        bank = "" if r["bank"] == "-" else f" b{r['bank']}"
        if r["role"] in ("gap", "free"):
            sym = display_symbol(r)
            link = r["group"] + ".md"
        else:
            sym = f"[`{r['symbol']}`]({r['group']}.md#s-{r['symbol']})"
            link = r["group"] + ".md"
        out.append(
            f'| <a id="a-{r["addr"][1:]}{bank.replace(" ", "")}"></a>`{r["addr"]}`{bank} '
            f"| {sym} | [{r['group']}]({link}) | {evidence(r['verify'])} |"
        )
    return block("addresses", out)


def name_index_block(rows) -> str:
    # Slots 2..N of a repeated structure are left out: 1,509 of the 2,892 rows
    # are `wBoxMon14Status` and its siblings, and a list nobody can read is not
    # an index. Their slot-1 row carries the count and the stride, and
    # `atlas.tsv` remains the exhaustive, greppable list — which is how anyone
    # actually looks up a name like that.
    listed = [r for r in rows if r["role"] not in ("gap", "free", "instance")]
    listed.sort(key=lambda r: (r["symbol"].lower(), r["addr_i"]))
    out = ["| symbol | address | bytes | chapter | ev |", "|---|---|---:|---|:--:|"]
    for r in listed:
        bank = "" if r["bank"] == "-" else f" b{r['bank']}"
        target = f"{r['group']}.md#s-{r['symbol']}" if r["role"] == "entry" else f"{r['group']}.md"
        out.append(
            f"| [`{r['symbol']}`]({target}) | `{r['addr']}`{bank} | {size(r['len_i'])} "
            f"| [{r['group']}]({r['group']}.md) | {evidence(r['verify'])} |"
        )
    return block("names", out)


# --- structures ------------------------------------------------------------

STRUCTS = [
    (
        "party_struct",
        "wPartyMon1",
        "wPartyMon2",
        "One of the six Pokemon you carry. Also the shape the link cable sends, "
        "and the shape a trainer's team is built in.",
    ),
    (
        "box_struct",
        "wBoxMon1",
        "wBoxMon2",
        "One of the twenty in a PC box: `party_struct` with the level and the five "
        "computed stats removed, because a stored Pokemon's stats are recalculated "
        "when it is withdrawn.",
    ),
    (
        "battle_struct",
        "wBattleMon",
        None,
        "The active Pokemon while a battle runs. Not the party shape: original "
        "trainer, experience and stat experience are gone, so the level and the "
        "stats sit at different offsets. Confusing the two is the classic way to "
        "produce a level 6,400 Pokemon.",
    ),
    (
        "battle_struct (opponent)",
        "wEnemyMon",
        None,
        "The same 29 bytes for the other side.",
    ),
    (
        "day-care lodger",
        "wDayCareMon",
        None,
        "One `box_struct` on its own, with its name and OT beside it.",
    ),
]


def struct_block(rows) -> str:
    by_symbol = {r["symbol"]: r for r in rows}
    out = []
    for title, first, second, blurb in STRUCTS:
        base = by_symbol.get(first)
        if base is None:
            continue
        fields = [
            r
            for r in rows
            if r["symbol"].startswith(first)
            and r["symbol"] != first
            and r["region"] == base["region"]
            and r["addr_i"] >= base["addr_i"]
        ]
        # Keep only the fields of *this* slot: everything up to the next slot.
        if second and second in by_symbol:
            end = by_symbol[second]["addr_i"]
        else:
            end = max((f["addr_i"] + max(f["len_i"], 1)) for f in fields) if fields else base["addr_i"]
        fields = [f for f in fields if f["addr_i"] < end]
        fields.sort(key=lambda r: (r["addr_i"], r["symbol"]))
        total = end - base["addr_i"]
        out.append(f"### `{title}` — {total} bytes")
        out.append("")
        out.append(blurb)
        out.append("")
        out.append(f"Base `{first}` at `{base['addr']}`.")
        out.append("")
        out.append("| offset | bytes | field | notes |")
        out.append("|---:|---:|---|---|")
        seen = set()
        for f in fields:
            off = f["addr_i"] - base["addr_i"]
            names = [g["symbol"] for g in fields if g["addr_i"] == f["addr_i"]]
            if f["addr_i"] in seen:
                continue
            seen.add(f["addr_i"])
            label = " / ".join(f"`{n[len(first):] or n}`" for n in names)
            here = [g["desc"] for g in fields if g["addr_i"] == f["addr_i"] and g["desc"]]
            out.append(f"| {off} | {size(f['len_i'])} | {label} | {here[0] if here else ''} |")
        out.append("")
    return block("structs", out)


# ---------------------------------------------------------------------------
# splicing
# ---------------------------------------------------------------------------


class MarkerLost(Exception):
    """A page that exists has lost a marker.  Refuse rather than overwrite."""


def splice(text: str, name: str, body: str, stub: str, existed: bool) -> str:
    """Replace one generated block inside `text`.

    Operates on the text it is handed, never on the file — a page may carry
    several blocks, and re-reading the file between them would leave only the
    last one applied.

    **A page that exists and has lost its marker is an error, not a rebuild.**
    Falling back to `stub` here once silently replaced twenty-one pages of
    hand-written prose with a four-line placeholder, because the marker's own
    wording had been edited and no longer matched.  The stub is only ever used
    to create a page that is not there yet.
    """
    begin, end = BEGIN.format(name), END.format(name)
    if begin not in text or end not in text:
        if existed:
            raise MarkerLost(name)
        text = stub
    i = text.index(begin)
    j = text.index(end) + len(end)
    return text[:i] + body + text[j:]


def worked_example_block(rows, symbol: str = "wPartyCount") -> str:
    """One entry, read column by column — generated so it cannot go stale.

    The README's job is to make somebody able to parse `atlas.tsv` without
    reading this script, and the fastest way to do that is one real row with
    every cell named. Typing it out by hand would make it the one line on the
    page that is allowed to be wrong.
    """
    row = next((r for r in rows if r["symbol"] == symbol), None)
    if row is None:
        return block("example", ["*(no such entry)*"])
    cols = ["region", "bank", "addr", "len", "symbol", "role", "sect", "group",
            "verify", "desc"]
    meanings = {
        "region": "which of the CPU's address ranges it is in",
        "bank": "the bank, or `-` where the region is not banked",
        "addr": "the CPU address, `$` then four uppercase hex digits",
        "len": "bytes this symbol owns before the next named address",
        "symbol": "the label, as the disassembly spells it",
        "role": "`entry`, `alias`, `instance`, `gap` or `free`",
        "sect": "the linker section it was declared in",
        "group": "our chapter — [`tools/chapters.py`](tools/chapters.py) decides it",
        "verify": "the evidence, comma separated: `rom`, `live`, `inv`",
        "desc": "what it is, in our own words — empty when nobody has written one",
    }
    raw = "\t".join(row.get(c, "") for c in cols)
    out = [
        "```text",
        "\t".join(cols),
        raw,
        "```",
        "",
        "| column | value | what it means |",
        "|---|---|---|",
    ]
    for c in cols:
        v = row.get(c, "")
        cell = f"`{v}`" if v else "*(empty)*"
        if c == "desc" and v:
            cell = v
        out.append(f"| `{c}` | {cell} | {meanings[c]} |")
    ev = row.get("verify", "")
    toks = [t for t in ev.split(",") if t]
    names = {"rom": "the cartridge names this address as an instruction operand",
             "live": "the byte changed while the cartridge ran the fixed script",
             "inv": "a named invariant proved it means what it says"}
    out += ["", f"So `{symbol}` carries **{evidence(ev)}**: "
            + "; ".join(names[t] for t in toks) + "."]
    return block("example", out)


def check_anchors() -> list[str]:
    """Every `page.md#s-…` / `#a-…` link must land on an anchor that exists.

    A plain link checker verifies that a link's *file* exists and deliberately
    does not look at fragments, so an index of 2,400 anchored links would
    otherwise be able to rot silently. It did, in the atlas's first life:
    aliases were linked before they were given anchors, and 370 links pointed
    at nothing.

    Anchors are also this repository's public URL surface — `docs/party.md#s-
    wPartyCount` is meant to be linked to from outside — so this runs on every
    build rather than only when the pages are rewritten.
    """
    import collections

    anchors: dict[str, set[str]] = collections.defaultdict(set)
    for path in sorted(os.listdir(DIR)):
        if not path.endswith(".md"):
            continue
        text = open(os.path.join(DIR, path), encoding="utf-8").read()
        for m in re.finditer(r'<a id="([^"]+)">', text):
            anchors[path].add(m.group(1))
    broken = []
    # The chapter pages and the two indexes link each other by bare filename;
    # the repository README reaches them through `docs/`.
    scan = [(os.path.join(DIR, p), "") for p in sorted(os.listdir(DIR))
            if p.endswith(".md")]
    scan.append((os.path.join(REPO, "README.md"), "docs/"))
    for path, prefix in scan:
        if not os.path.exists(path):
            continue
        text = open(path, encoding="utf-8").read()
        for m in re.finditer(r"\]\(" + re.escape(prefix) + r"([a-z0-9-]+\.md)#([^)]+)\)", text):
            target, frag = m.group(1), m.group(2)
            if frag.startswith(("s-", "a-")) and frag not in anchors.get(target, set()):
                broken.append(f"{os.path.relpath(path, REPO)} -> {prefix}{target}#{frag}")
    return broken


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = read_atlas()
    jobs = []

    # The repository README is the front page and carries the headline figures,
    # so they are generated too: a README that claimed 2,898 entries while the
    # data held 2,900 would be the most visible lie in the project.
    jobs.append(
        (
            os.path.join(REPO, "README.md"),
            [("coverage", coverage_block(rows)), ("evidence", evidence_block(rows)),
             ("chapters", chapter_index_block(rows, prefix="docs/")),
             ("example", worked_example_block(rows))],
            readme_stub(),
        )
    )
    jobs.append((os.path.join(DIR, "by-address.md"),
                 [("addresses", address_index_block(rows))], index_stub("address")))
    jobs.append((os.path.join(DIR, "by-name.md"),
                 [("names", name_index_block(rows))], index_stub("name")))
    jobs.append((os.path.join(DIR, "structures.md"),
                 [("structs", struct_block(rows))], structures_stub()))
    present = {r["group"] for r in rows}
    for name in chapters_mod.CHAPTERS:
        if name not in present:
            continue
        jobs.append((os.path.join(DIR, f"{name}.md"),
                     [("table", chapter_table(rows, name))], chapter_stub(name)))

    stale = []
    for path, blocks, stub in jobs:
        rel = os.path.relpath(path, REPO)
        before = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        text = before if before is not None else stub
        for bname, body in blocks:
            try:
                text = splice(text, bname, body, stub, existed=before is not None)
            except MarkerLost as lost:
                print(f"FAIL — {rel} has no `{lost.args[0]}` marker pair.")
                print(f"  Expected: {BEGIN.format(lost.args[0])}")
                print("  The page exists, so this is not rebuilt from the stub: that would")
                print("  throw away everything written outside the markers. Put the marker")
                print("  back, or delete the page if you really want it regenerated.")
                return 1
        if text != before:
            stale.append(rel if before is not None else f"{rel} (new)")
        if not args.check:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(text)

    broken = check_anchors()
    if broken:
        print("FAIL — the atlas pages contain dead anchor links:")
        for b in broken[:10]:
            print(f"  {b}")
        if len(broken) > 10:
            print(f"  ... and {len(broken) - 10} more")
        return 1

    if args.check:
        if stale:
            print("FAIL — the atlas pages are stale; run `make docs`:")
            for s in stale:
                print(f"  {s}")
            return 1
        print(f"OK — {len(jobs)} atlas pages match {os.path.relpath(ATLAS, REPO)}")
        return 0

    print(f"Wrote {len(jobs)} pages from {len(rows):,} atlas entries")
    return 0


# ---------------------------------------------------------------------------
# stubs — the shape of a page the first time it is generated.  Everything
# outside the markers is preserved afterwards, so this is a starting point, not
# a template that overwrites your writing.
# ---------------------------------------------------------------------------


def readme_stub() -> str:
    return f"""# AtlasGB

Placeholder — see the generated blocks below.

## Coverage

{block("coverage", [])}

## Evidence

{block("evidence", [])}

## A worked example

{block("example", [])}

## Chapters

{block("chapters", [])}
"""


def index_stub(kind: str) -> str:
    name = "address" if kind == "address" else "name"
    return f"""# The atlas, by {name}

[← AtlasGB](../README.md)

{block("addresses" if kind == "address" else "names", [])}
"""


def structures_stub() -> str:
    return f"""# The structures

[← AtlasGB](../README.md)

{block("structs", [])}
"""


def chapter_stub(name: str) -> str:
    blurb = chapters_mod.CHAPTERS[name]
    return f"""# {name}

[← AtlasGB](../README.md) · [by address](by-address.md) · [by name](by-name.md)

{blurb}

{block("table", [])}
"""


if __name__ == "__main__":
    sys.exit(main())
